server:
  address: ${SERVER_ADDRESS}
  port: ${CONFIG_PORT}


spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configurations
    discovery:
      enabled: true


# Eureka Service Discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_PORT}/eureka

application:
  kafka-path: ${KAFKA_PATH}