server:
  port: ${CONTAINER_PORT}


spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configurations


# Eureka Service Discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8190/eureka

application:
  kafka-path: /Users/user/Downloads/kafka_server