server:
  port: 8222

spring:
  config:
    import: optional:classpath:/configurations/dev/common-dev.yml
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true


application:
  test: test-dev