server:
  port: 8201
  servlet:
    context-path: /user-service

spring:
  config:
    import: optional:classpath:/configurations/dev/common-dev.yml
#  datasource:
#    enable: true
#    liquibase: classpath:/db/changelog/db.changelog-master.yaml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: mail.smtp2go.com
    port: 587
    username: pangeanis.com
    password: EG4QKkxv13uItbC9
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


application:
  test: test-dev
