server:
  port: 8222

spring:
  #  config:
#    import: optional:classpath:/configurations/local/common-local.yml
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-methods: "*"
#            allowed-headers: "*"
#            allow-credentials: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/?(?<segment>.*), /${segment}
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/?(?<segment>.*), /${segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
  main:
    web-application-type: reactive

# Eureka Service Discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8190/eureka

application:
  kafka-path: /Users/user/Downloads/kafka_server
  security:
    api-key: $2a$12$P5FCQMKoJeRcjeN036mL.ehAvjzwfiduyP4DzjIqWxllQRklNIWYW
    jwt:
      secret-key: G2Cps5vY7C6nenipYHty/gvSdv2bjd22Q8BKIF1hR3I=
      expiration: 15552000000
      refresh-token:
        expiration: 31536000000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
#    urls:
#      - name: user-service
#        url: /user-service/v3/api-docs
#      - name: post-service
#        url: /post-service/v3/api-docs