server:
  port: 8222

spring:
  main:
    allow-bean-definition-overriding: true
  #  config:
#    import: optional:classpath:/configurations/local/common-local.yml
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true


# Eureka Service Discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8190/eureka

application:
  kafka-path: /Users/user/Downloads/kafka_server
  security:
    api-key: $2a$12$P5FCQMKoJeRcjeN036mL.ehAvjzwfiduyP4DzjIqWxllQRklNIWYW
    jwt:
      secret-key: G2Cps5vY7C6nenipYHty/gvSdv2bjd22Q8BKIF1hR3I=
      expiration: 15552000000
      refresh-token:
        expiration: 31536000000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: post-service
        url: /post-service/v3/api-docs


