spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/tringgs
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Eureka Service Discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8190/eureka

application:
  kafka-path: /Users/user/Downloads/kafka_server
  security:
    api-key: $2a$12$P5FCQMKoJeRcjeN036mL.ehAvjzwfiduyP4DzjIqWxllQRklNIWYW
    jwt:
      secret-key: G2Cps5vY7C6nenipYHty/gvSdv2bjd22Q8BKIF1hR3I=
      expiration: 15552000000
      refresh-token:
        expiration: 31536000000

springdoc:
  swagger-ui:
    use-root-path: true

