server:
  port: 8201
  servlet:
    context-path: /user-service

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  config:
    import: optional:classpath:/configurations/local/common-local.yml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: mail.smtp2go.com
    port: 587
    username: pangeanis.com
    password: EG4QKkxv13uItbC9
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


openapi:
  service:
    title: user-service doc
    version: 1.0.0
    url: http://localhost:8222